/** Stable machine-readable error codes returned in the `code` field of every API error. */
export const ErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  FORBIDDEN: 'FORBIDDEN',
  WAREHOUSE_FORBIDDEN: 'WAREHOUSE_FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  IMEI_ALREADY_EXISTS: 'IMEI_ALREADY_EXISTS',
  IMEI_INVALID: 'IMEI_INVALID',
  IMEI_NOT_FOUND: 'IMEI_NOT_FOUND',
  IMEI_DUPLICATE_IN_REQUEST: 'IMEI_DUPLICATE_IN_REQUEST',
  IMEI_WRONG_WAREHOUSE: 'IMEI_WRONG_WAREHOUSE',
  IMEI_NOT_AVAILABLE: 'IMEI_NOT_AVAILABLE',
  IMEI_ALREADY_SOLD: 'IMEI_ALREADY_SOLD',
  IMEI_NOT_IN_TRANSFER: 'IMEI_NOT_IN_TRANSFER',
  IMEI_WRONG_PRODUCT: 'IMEI_WRONG_PRODUCT',

  SERIAL_NOT_FOUND: 'SERIAL_NOT_FOUND',
  SERIAL_ALREADY_EXISTS: 'SERIAL_ALREADY_EXISTS',
  SERIAL_DUPLICATE_IN_REQUEST: 'SERIAL_DUPLICATE_IN_REQUEST',
  PRODUCT_BARCODE_NOT_FOUND: 'PRODUCT_BARCODE_NOT_FOUND',
  UNRECOGNIZED_BARCODE: 'UNRECOGNIZED_BARCODE',

  QUANTITY_EXCEEDED: 'QUANTITY_EXCEEDED',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  TRACKING_MODE_MISMATCH: 'TRACKING_MODE_MISMATCH',
  PARTIAL_RECEIPT_NOT_ALLOWED: 'PARTIAL_RECEIPT_NOT_ALLOWED',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  ALREADY_RECEIVED: 'ALREADY_RECEIVED',
  CONCURRENT_MODIFICATION: 'CONCURRENT_MODIFICATION',
  DUPLICATE_CODE: 'DUPLICATE_CODE',
} as const;
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ApiError {
  statusCode: number;
  code: ErrorCode | string;
  message: string;
  details?: Record<string, unknown>;
}
